-- GUI Generated by Roblox GUI Builder (Layout Only)
local ScreenGui = Instance.new("ScreenGui")
ScreenGui.Name = "MyGeneratedGui"
ScreenGui.ResetOnSpawn = false
ScreenGui.Parent = game.Players.LocalPlayer:WaitForChild("PlayerGui")

local Frame1 = Instance.new("Frame")
Frame1.Name = "Frame1"
Frame1.Parent = ScreenGui
Frame1.Position = UDim2.new(-0.5, -150, -0.5, -100)
Frame1.Size = UDim2.new(0, 500, 0, 300)
Frame1.BackgroundColor3 = Color3.fromRGB(30, 41, 59)
Frame1.BorderSizePixel = 0
local Frame1Corner = Instance.new("UICorner")
Frame1Corner.CornerRadius = UDim.new(0, 10)
Frame1Corner.Parent = Frame1

local TextLabel3 = Instance.new("TextLabel")
TextLabel3.Name = "TextLabel3"
TextLabel3.Parent = ScreenGui
TextLabel3.ZIndex = 2
TextLabel3.Position = UDim2.new(0, 20, 0, 20)
TextLabel3.Size = UDim2.new(0, 1, 0, 40)
TextLabel3.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
TextLabel3.BackgroundTransparency = 1
TextLabel3.BorderSizePixel = 0
TextLabel3.Text = "Label"
TextLabel3.TextSize = 18
TextLabel3.TextColor3 = Color3.fromRGB(255, 255, 255)
TextLabel3.Font = Enum.Font.SourceSansBold

