local DrRay = loadstring(game:HttpGet("https://raw.githubusercontent.com/AZYsGithub/DrRay-UI-Library/main/DrRay.lua"))()
local Window = DrRay:Load("Мой скрипт", "rbxassetid://14133403065")
local Tab = Window:newTab("Главная")
Tab:Button("Нажми меня", "Описание кнопки", function()
    print("Кнопка нажата!")
end)
